name: Build

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  pod-lint:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.0"
      - uses: actions/checkout@v2
      - name: Run lint
        run: pod lib lint --allow-warnings
